/** All 18 Pokémon types (Gen 1 species may carry later-gen typings, e.g. Fairy). */
export type PokemonType =
  | "normal"
  | "fire"
  | "water"
  | "electric"
  | "grass"
  | "ice"
  | "fighting"
  | "poison"
  | "ground"
  | "flying"
  | "psychic"
  | "bug"
  | "rock"
  | "ghost"
  | "dragon"
  | "dark"
  | "steel"
  | "fairy";

export type PokemonId = number;

/**
 * Normalized reference data for one Pokémon.
 * Generated by scripts/sync-pokemon-data.ts into src/data/pokemon.json.
 */
export interface Pokemon {
  id: PokemonId;
  /** Korean official name — the answer players type (MVP). */
  nameKo: string;
  /** English slug (sprite lookups / future). */
  nameEn: string;
  generation: number;
  /** Ordered by slot (primary type first). */
  types: PokemonType[];
  /** Pre-normalized set of strings accepted as correct (see normalizeKoreanName). */
  acceptedAnswers: string[];
  // Sprite paths are NOT stored here — they are derived from `id` via
  // shared/sprites.ts (spritePath), since /sprites/{variant}/{id}.png is pure convention.
}
